[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 5

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00a651"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#e6edf3"
font = "sans serif"

[runner]
fastReruns = true
